### ISSUE TITLE
decrypted files cannot be viewed

### ISSUE THREAD

**Issue by Edmund1645** [RealityNet/kobackupdec#18]
I have been able to successfully decrypt the files and they have the correct extensions now, but anytime I try to open, the files appear to be damaged.

at first, the files were read-only, but then I was able to solve it using this #16

**Comment by dfirfpi** [comment]
Hi @Edmund1645 
which files are you unable to open? application data? media? every file?

From my point of view is not possible to solve such an issue... please provide more details.

**Comment by jt-byte** [comment]
Hi @dfirfpi, I probably have the same problem. In my case it seems that media files are not decrypted by the kobackupdec script. there is no file header at all, an all data look very randomized

Best regards
Jens

**Comment by dfirfpi** [comment]
@jt-byte thanks for reaching out. To be able to address the issue I need a sample: are you able to re-create this scenario? Or to sanitize the current one? I mean: leave the folder structure of media with the info.xml and just a couple of files. Let me know

**Comment by realSnoopy** [comment]
read only only matters when using the script in linux. are you sure, the files are successfully encrypted? please try -vvv to see the info, debug output, correct file-extension is no proof of correct decrypting, because the filenames are not encrypted. when the files are audio files, see my pullrequest for missing audio conversation, this can be easily fixed

**Comment by dfirfpi** [comment]
Try again as suggested by @realSnoopy.
Reopen the issue or a new one if you have news.
Thanks
